MVC_Test_Case/MVC_Test_Case/Models/Users.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace MVC_Test_Case.Models
{
    public class User
    {
        [Key]
        public int ID { get; set; }

        [Required(ErrorMessage = "This field is required.")]
        public string Name { get; set; }

        [Required(ErrorMessage = "This field is required.")]
        public string Surname { get; set; }

        [Required(ErrorMessage = "This field is required.")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }

    
    public class UserDBContext : DbContext
    {
        public DbSet<User> Users { get; set; }
    }
}

MVC_Test_Case/MVC_Test_Case/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Core;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using MVC_Test_Case.Models;

namespace MVC_Test_Case.Controllers
{
    public class UsersController : Controller
    {
        string tempPass;
        private UserDBContext db = new UserDBContext();

        public static string CreateMD5(string input)
        {
            // Use input string to calculate MD5 hash
            using (System.Security.Cryptography.MD5 md5 = System.Security.Cryptography.MD5.Create())
            {
                byte[] inputBytes = System.Text.Encoding.ASCII.GetBytes(input);
                byte[] hashBytes = md5.ComputeHash(inputBytes);

                // Convert the byte array to hexadecimal string
                StringBuilder sb = new StringBuilder();
                for (int i = 0; i < hashBytes.Length; i++)
                {
                    sb.Append(hashBytes[i].ToString("X2"));
                }
                return sb.ToString();
            }
        }

        // GET: Users
        public ActionResult Home()
        {
            return View();
        }

        // GET: Users/Login
        public ActionResult Login()
        {
            Session["isSuccess"] = false;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(User user)
        {

            if (Session["Name"] != null)
            {
                ViewBag.Error = "You are already logged in";
                return View("Login");
            }

            if (!String.IsNullOrEmpty(user.Name) && !String.IsNullOrEmpty(user.Password))
            {
                tempPass = CreateMD5(user.Password);

                if (db.Users.Any(x => x.Name == user.Name && tempPass == x.Password))
                {
                    Session["Name"] = user.Name;

                    return RedirectToAction("Home");
                }
                else
                {
                    ViewBag.ErrorMessage = "Incorrect name or password !!";
                }
            }

            else
            {
                ViewBag.ErrorMessage2 = "Please type your name and password !!";
            }

            
            return View();
        }

        // GET: Users/Register
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [OutputCache(NoStore = true, Duration = 0)]
        public ActionResult Register(User user)
        {
            if (ModelState.IsValid)
            {
                if (db.Users.Any(x => x.Name == user.Name)) {

                    ViewBag.ErrorMessage = "Account with this name already exists !!";

                    return View("Register");
                }

                else { 
                    user.Password = CreateMD5(user.Password);
                    db.Users.Add(user);
                    db.SaveChanges();

                    ModelState.Clear();

                    ViewBag.Message = "You have successfully registered.";
                }
            }

            return View("Register");
        }

        // GET: Users/Logout
        public ActionResult Logout()
        {
            Session["Name"] = null;
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC_Test_Case/MVC_Test_Case/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="navbar-brand form-inline">MVC_Case</li>

                    <li>@Html.ActionLink("Home", "Home", "Users")</li>
                </ul>
                <div class="navbar-right">
                    <ul class="nav navbar-nav">
                        @if (Session["Name"] == null)
                        {
                            <li>@Html.ActionLink("Register", "Register", "Users")</li>
                        }

                        @if (Session["Name"] == null)
                        {

                            <li>@Html.ActionLink("Login", "Login", "Users")</li>
                        }
                        @if (Session["Name"] != null)
                        {
                            <li>@Html.ActionLink("Logout", "Logout", "Users")</li>
                        }
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MVC_Test_Case/MVC_Test_Case/Views/Users/Home.cshtml
@{
    ViewBag.Title = "Home";
}

@if (Session["Name"] != null)
{
    <h2 class="text-center">Welcome @Session["Name"].ToString().ToUpper()</h2>
}
else
{
    <h2 class="text-center">Access Denied</h2>
    <p class="text-center">
        You must be logged in to view this page.
    </p>
}

MVC_Test_Case/MVC_Test_Case/Views/Users/Login.cshtml
@model MVC_Test_Case.Models.User

@{
    ViewBag.Title = "Login";
}

<body>

    <h2>Login</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Login" class="btn btn-default" />
                </div>
            </div>
        </div>

        <p class="bg-warning ">@ViewBag.Error</p>
        <p class="bg-danger ">@ViewBag.ErrorMessage</p>
        <p class="bg-danger ">@ViewBag.ErrorMessage2</p>
    }

</body>

MVC_Test_Case/MVC_Test_Case/Views/Users/Logout.cshtml
@{
    ViewBag.Title = "Logout";
}
<body>
    <div class="text-center">
        <h1 class="display-4">Logout Successful</h1>
        @if (Session["Name"] == null)
        {
            <p class="display-4">You have logged out successfully.</p>
        }


    </div>
</body>

MVC_Test_Case/MVC_Test_Case/Views/Users/Register.cshtml
@model MVC_Test_Case.Models.User

@{
    ViewBag.Title = "Register";
}

<h2>Register</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Register" class="btn btn-default" />
        </div>
    </div>


    <p class="bg-warning ">@ViewBag.ErrorMessage</p>

    <p class="bg-success ">@ViewBag.Message</p>


</div>
}

<div>
    @Html.ActionLink("Go Back", "Login")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}